/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import java.awt.Color;
import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import twitter4j.Status;
import twitter4j.TwitterException;
import twitter4j.User;
import utils.Listeners;
import static ventanas.PantallaLogin.gestionTwitter;

/**
 *
 * @author Annie
 */
public class Tweet extends javax.swing.JPanel implements Serializable {

    // ATRIBUTOS
    private String nombreUsuario;
    private String id;
    private String retweets;
    private String textoTweet;
    private boolean favorito;

    private SimpleDateFormat sdf;
    private Status tweet;

    private Listeners listeners;
    final Color azulOscuro = new Color(29, 161, 242);
    final Color azulClaro = new Color(128, 216, 255);
    final Color rojoClaro = new Color(255, 0, 0);
    final Color rojoOscuro = new Color(200, 0, 0);
    final Color colorBotonFavorito;

    public Tweet() {
        initComponents();
        listeners = new Listeners();
        sdf = new SimpleDateFormat("dd-MM-yyyy");
        aplicarListenerBotones();
        this.textAreaTweet.setEditable(false);
        this.colorBotonFavorito = this.jButtonLike.getBackground();
    }

    public void inicializarComponente(Status tweet) {
        try {
            this.tweet = tweet;
            setFecha(tweet.getCreatedAt());
            setNombreUsuario(tweet.getUser().getName());
            setId("@" + tweet.getUser().getScreenName());
            setRetweets(Integer.toString(tweet.getRetweetCount()));
            setFotoUsuario();
            setTextoTweet(tweet.getText());
        } catch (IllegalStateException ex) {
            System.out.println(ex.getMessage());
        }
    }

    // GETTER Y SETTER
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
        this.jLabelUsuario.setText(nombreUsuario);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
        this.jLabelId.setText(id);
    }

    public String getRetweets() {
        return retweets;
    }

    public void setRetweets(String retwets) {
        this.retweets = retwets;
        this.textAreaTweet.setText(retwets);
    }

    public String getTextoTweet() {
        return textoTweet;
    }

    public void setTextoTweet(String textoTweet) {
        String texto = dividirTexto(textoTweet);
        this.textoTweet = texto;
        this.textAreaTweet.setText(texto);
    }

    public Icon getFotoUsuario() {
        return this.jLabelFoto.getIcon();
    }

    public void setFotoUsuario() {
        try {
            User usuario = tweet.getUser();
            URL urlImagen = new URL(usuario.getProfileImageURL());
            ImageIcon imagen = new ImageIcon(urlImagen);
            jLabelFoto.setIcon(imagen);
        } catch (IllegalStateException | MalformedURLException ex) {
            Logger.getLogger(NuevoTweet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setFecha(Date fecha) {
        this.jLabelFecha.setText(sdf.format(fecha));
    }

    private String dividirTexto(String textoTweet) {
        String[] palabras = textoTweet.split(" ");
        String texto = "";
        int letras = 0;

        for (String palabra : palabras) {
            letras += palabra.length();
            texto += palabra;
            if (letras >= 60) {
                texto += "\n";
                letras = 0;
            } else {
                texto += " ";
                letras++;
            }
        }
        return texto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFoto = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jButtonRetweet = new javax.swing.JButton();
        jButtonLike = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaTweet = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 196, 255)));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(700, 115));
        setLayout(null);

        jLabelFoto.setMaximumSize(new java.awt.Dimension(48, 48));
        jLabelFoto.setMinimumSize(new java.awt.Dimension(48, 48));
        jLabelFoto.setPreferredSize(new java.awt.Dimension(48, 48));
        add(jLabelFoto);
        jLabelFoto.setBounds(10, 10, 100, 100);

        jLabelUsuario.setText("Usuario");
        add(jLabelUsuario);
        jLabelUsuario.setBounds(120, 10, 150, 15);

        jLabelId.setText("Id");
        add(jLabelId);
        jLabelId.setBounds(280, 10, 160, 15);

        jLabelFecha.setText("Fecha");
        add(jLabelFecha);
        jLabelFecha.setBounds(450, 10, 110, 15);

        jButtonRetweet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refrescar_blanco.png"))); // NOI18N
        jButtonRetweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetweetActionPerformed(evt);
            }
        });
        add(jButtonRetweet);
        jButtonRetweet.setBounds(600, 10, 40, 40);

        jButtonLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/corazon_blanco.png"))); // NOI18N
        jButtonLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLikeActionPerformed(evt);
            }
        });
        add(jButtonLike);
        jButtonLike.setBounds(650, 10, 40, 40);

        textAreaTweet.setColumns(20);
        textAreaTweet.setRows(5);
        jScrollPane1.setViewportView(textAreaTweet);

        add(jScrollPane1);
        jScrollPane1.setBounds(120, 60, 570, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLikeActionPerformed

        this.favorito = !this.favorito;
        if (favorito) {
            gestionTwitter.darFavorito(this.tweet.getId());
            listeners.cambiarColorAlPasarPorEncima(jButtonLike, rojoClaro, rojoOscuro);
            this.jButtonLike.setBackground(rojoClaro);
        } else {
            gestionTwitter.quitarFavorito(this.tweet.getId());
            listeners.cambiarColorAlPasarPorEncima(jButtonLike, azulClaro, azulOscuro);
            this.jButtonLike.setBackground(this.colorBotonFavorito);
        }
    }//GEN-LAST:event_jButtonLikeActionPerformed

    private void jButtonRetweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetweetActionPerformed
        gestionTwitter.retwitearTweet(tweet);
        JOptionPane.showMessageDialog(this, "Se ha retuiteado correctamente");
    }//GEN-LAST:event_jButtonRetweetActionPerformed

    private void aplicarListenerBotones() {
        listeners.cambiarColorAlPasarPorEncima(jButtonLike, azulClaro, azulOscuro);
        listeners.cambiarColorAlPasarPorEncima(jButtonRetweet, azulClaro, azulOscuro);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLike;
    private javax.swing.JButton jButtonRetweet;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaTweet;
    // End of variables declaration//GEN-END:variables
}
