/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mdlaf.MaterialLookAndFeel;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialColors;
import twitter4j.Status;
import twitter4j.User;
import static ventanas.PantallaLogin.gestionTwitter;

/**
 *
 * @author Annie
 */
public class Usuario extends javax.swing.JPanel implements Serializable {

    private String nombreUsuario;
    private String id;

    private Status tweet;

    public Usuario() {
        initComponents();
        
    }

    public void inicializarComponente(Status tweet) {
        try {
            this.tweet = tweet;

            setNombreUsuario(tweet.getUser().getName());
            setId("@" + tweet.getUser().getScreenName());

            setFotoPerfil();
            setFotoPortada();
        } catch (IllegalStateException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void setFotoPerfil() {
        try {
            User usuario = gestionTwitter.getUsuario();
            URL urlImagen = new URL(usuario.getProfileImageURL());
            ImageIcon imagenUsuario = new ImageIcon(urlImagen);
            jLabelFotoUsuario.setIcon(imagenUsuario);
        } catch (IllegalStateException | MalformedURLException ex) {
            Logger.getLogger(NuevoTweet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //COMPROBAR SI .getProfileBannerURL() ES EL METODO CORRECTO PARA PONER IMAGEN DE PORTADA
    public void setFotoPortada() {
        try {
            User usuario = gestionTwitter.getUsuario();
            URL urlImagen = new URL(usuario.getProfileBannerURL());
            ImageIcon imagenPortada = new ImageIcon(urlImagen);
            jLabelFotoPortada.setIcon(imagenPortada);
        } catch (IllegalStateException | MalformedURLException ex) {
            Logger.getLogger(NuevoTweet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String getNombreUsuario() {
        return nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
        this.jLabelNombreUsuario.setText(nombreUsuario);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
        this.jLabelIdUsuario.setText(id);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFotoUsuario = new javax.swing.JLabel();
        jLabelFotoPortada = new javax.swing.JLabel();
        jLabelIdUsuario = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(209, 20));
        setMinimumSize(new java.awt.Dimension(209, 20));
        setPreferredSize(new java.awt.Dimension(209, 20));
        setLayout(null);

        jLabelFotoUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelFotoUsuario);
        jLabelFotoUsuario.setBounds(30, 50, 60, 60);

        jLabelFotoPortada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelFotoPortada);
        jLabelFotoPortada.setBounds(0, 0, 370, 80);

        jLabelIdUsuario.setText("@Usuario");
        jLabelIdUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelIdUsuario);
        jLabelIdUsuario.setBounds(190, 120, 170, 24);

        jLabelNombreUsuario.setText("NombreUsuario");
        jLabelNombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelNombreUsuario);
        jLabelNombreUsuario.setBounds(10, 120, 170, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFotoPortada;
    private javax.swing.JLabel jLabelFotoUsuario;
    private javax.swing.JLabel jLabelIdUsuario;
    private javax.swing.JLabel jLabelNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
