/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import dto.UsuarioTwitter;
import java.io.Serializable;
import javax.swing.ImageIcon;
import twitter4j.User;

/**
 *
 * @author Annie
 */
public class Usuario extends javax.swing.JPanel implements Serializable {

    private UsuarioTwitter usuario;

    public Usuario() {
        initComponents();
    }

    public void inicializarComponente(User usuario) {
        this.usuario = new UsuarioTwitter(usuario);
        this.jLabelIdUsuario.setText(this.usuario.getIdUsuario());
        this.jLabelNombreUsuario.setText(this.usuario.getNombre());
        setFotoPerfil();
        //setFotoPortada();
    }

    public void setFotoPerfil() {
        if (this.usuario.getFotoPerfil() != null) {
            ImageIcon imagenUsuario = new ImageIcon(this.usuario.getFotoPerfil());
            if (imagenUsuario != null) {
                jLabelFotoUsuario.setIcon(imagenUsuario);
            }
        }
    }

    //COMPROBAR SI .getProfileBannerURL() ES EL METODO CORRECTO PARA PONER IMAGEN DE PORTADA
    public void setFotoPortada() {
        if (this.usuario.getFotoPortada() != null) {
            ImageIcon imagenPortada = new ImageIcon(this.usuario.getFotoPortada());
            if (imagenPortada != null) {
                jLabelFotoPortada.setIcon(imagenPortada);
            }
        }
    }

    public UsuarioTwitter getUsuario() {
        return usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFotoUsuario = new javax.swing.JLabel();
        jLabelFotoPortada = new javax.swing.JLabel();
        jLabelIdUsuario = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(360, 176));
        setMinimumSize(new java.awt.Dimension(360, 176));
        setPreferredSize(new java.awt.Dimension(360, 176));
        setLayout(null);

        jLabelFotoUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelFotoUsuario);
        jLabelFotoUsuario.setBounds(50, 50, 50, 50);

        jLabelFotoPortada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelFotoPortada);
        jLabelFotoPortada.setBounds(0, 0, 360, 80);

        jLabelIdUsuario.setText("@Usuario");
        jLabelIdUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelIdUsuario);
        jLabelIdUsuario.setBounds(190, 140, 150, 19);

        jLabelNombreUsuario.setText("NombreUsuario");
        jLabelNombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelNombreUsuario);
        jLabelNombreUsuario.setBounds(40, 140, 140, 19);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFotoPortada;
    private javax.swing.JLabel jLabelFotoUsuario;
    private javax.swing.JLabel jLabelIdUsuario;
    private javax.swing.JLabel jLabelNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
