/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import dto.UsuarioTwitter;
import java.awt.Color;
import java.io.File;
import java.io.Serializable;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import twitter4j.User;
import utils.Listeners;
import static utils.Listeners.azulClaro;
import static ventanas.PantallaLogin.gestionTwitter;
import static ventanas.PantallaLogin.padre;
import ventanas.PantallaUsuariosBuscados;

/**
 *
 * @author Annie
 */
public class Usuario extends javax.swing.JPanel implements Serializable {

    private UsuarioTwitter usuario;
    private Listeners listeners;

    public Usuario() {
        initComponents();
    }

    public void inicializarComponente(User usuario) {
        this.usuario = new UsuarioTwitter(usuario);
        this.jLabelIdUsuario.setText(this.usuario.getIdUsuario());
        this.jLabelNombreUsuario.setText(this.usuario.getNombre());
        this.jLabelSeguidos.setText(this.usuario.getTotalAmigos() + " seguidos");
        this.jLabelSeguidores.setText(this.usuario.getTotalSeguidores() + " seguidores");
        setFotoPerfil();
        setFotoPortada();
        this.listeners = new Listeners();
        listeners.cambiarColorAlPasarPorEncima(jLabelSeguidos, this.jLabelSeguidos.getBackground(), azulClaro);
        listeners.cambiarColorAlPasarPorEncima(jLabelSeguidores, this.jLabelSeguidores.getBackground(), azulClaro);
    }

    public void setFotoPerfil() {
        if (this.usuario.getFotoPerfil() != null) {
            ImageIcon imagenUsuario = new ImageIcon(this.usuario.getFotoPerfil());
            if (imagenUsuario != null) {
                jLabelFotoUsuario.setIcon(imagenUsuario);
            }
        } else {
            jLabelFotoUsuario.setIcon(new ImageIcon(getClass().getResource(File.separator + "img" + File.separator + "Twitter_Logo_Blue240.png")));
        }
    }

    //COMPROBAR SI .getProfileBannerURL() ES EL METODO CORRECTO PARA PONER IMAGEN DE PORTADA
    public void setFotoPortada() {
        if (this.usuario.getFotoPortada() != null) {
            ImageIcon imagenPortada = new ImageIcon(this.usuario.getFotoPortada());
            if (imagenPortada != null) {
                jLabelFotoPortada.setIcon(imagenPortada);
            }
        } else {
            jLabelFotoPortada.setBackground(new Color(128, 216, 255));
        }
    }

    public UsuarioTwitter getUsuario() {
        return usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIdUsuario = new javax.swing.JLabel();
        jLabelFotoUsuario = new javax.swing.JLabel();
        jLabelFotoPortada = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelSeguidores = new javax.swing.JLabel();
        jLabelSeguidos = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(360, 176));
        setMinimumSize(new java.awt.Dimension(360, 176));
        setPreferredSize(new java.awt.Dimension(360, 176));
        setLayout(null);

        jLabelIdUsuario.setText("@Usuario");
        jLabelIdUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelIdUsuario);
        jLabelIdUsuario.setBounds(50, 140, 140, 19);

        jLabelFotoUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelFotoUsuario);
        jLabelFotoUsuario.setBounds(50, 50, 50, 50);

        jLabelFotoPortada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelFotoPortada);
        jLabelFotoPortada.setBounds(0, 0, 360, 80);

        jLabelNombreUsuario.setText("NombreUsuario");
        jLabelNombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelNombreUsuario);
        jLabelNombreUsuario.setBounds(50, 110, 140, 19);

        jLabelSeguidores.setText("Seguidores");
        jLabelSeguidores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelSeguidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSeguidoresMouseClicked(evt);
            }
        });
        add(jLabelSeguidores);
        jLabelSeguidores.setBounds(200, 140, 140, 19);

        jLabelSeguidos.setText("Seguidos");
        jLabelSeguidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelSeguidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSeguidosMouseClicked(evt);
            }
        });
        add(jLabelSeguidos);
        jLabelSeguidos.setBounds(200, 110, 140, 19);

        jLabelFondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabelFondo);
        jLabelFondo.setBounds(0, 70, 360, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSeguidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSeguidosMouseClicked
        List<User> usuariosSeguidos = gestionTwitter.getSeguidos(this.usuario.getId());
        if (usuariosSeguidos != null) {
            PantallaUsuariosBuscados ventana = new PantallaUsuariosBuscados(padre, true, usuariosSeguidos);
            ventana.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(padre, "No sigues a ningún usuario");
        }
    }//GEN-LAST:event_jLabelSeguidosMouseClicked

    private void jLabelSeguidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSeguidoresMouseClicked
        List<User> usuariosSeguidores = gestionTwitter.getSeguidores(this.usuario.getId());
        if (usuariosSeguidores != null) {
            PantallaUsuariosBuscados ventana = new PantallaUsuariosBuscados(padre, true, usuariosSeguidores);
            ventana.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(padre, "No tienes ningún seguidor");
        }
    }//GEN-LAST:event_jLabelSeguidoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFotoPortada;
    private javax.swing.JLabel jLabelFotoUsuario;
    private javax.swing.JLabel jLabelIdUsuario;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelSeguidores;
    private javax.swing.JLabel jLabelSeguidos;
    // End of variables declaration//GEN-END:variables
}
