/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import componentes.TrendingTopic;
import componentes.Tweet;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import twitter4j.Status;
import twitter4j.Trend;
import utils.Listeners;
import static ventanas.PantallaLogin.BBDD;
import static ventanas.PantallaLogin.gestionTwitter;
import static ventanas.PantallaLogin.padre;

/**
 *
 * @author alumnop
 */
public class PantallaPrincipal extends javax.swing.JDialog {

    private ArrayList<TrendingTopic> componentesTrendingTopic;
    private ArrayList<Tweet> componentesTweet;
    private Listeners listener;
    
    /**
     * Creates new form TwitterMain2
     */
    public PantallaPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        generarListasComponentes();
        inicializarTweets();
        this.nuevoTweet.inicializarComponente();
        this.usuario.inicializarComponente(gestionTwitter.getUsuario());
        
        listener = new Listeners();
        aplicarListenerBotones();

        // MIENTRAS SE ENLAZA CON AJUSTES LLAMA A UNA LOCALIZACION CUALQUIERA
        HashMap<String, Integer> tt = BBDD.getWoeidTrendingTopic();
        String lugar = tt.keySet().iterator().next();
        inicializarTrendingTopics(lugar);   // Mantener este metodo

    }

    private void generarListasComponentes() {
        this.componentesTrendingTopic = new ArrayList<>();
        this.componentesTrendingTopic.add(trendingTopic1);
        this.componentesTrendingTopic.add(trendingTopic2);
        this.componentesTrendingTopic.add(trendingTopic3);
        this.componentesTrendingTopic.add(trendingTopic4);
        this.componentesTrendingTopic.add(trendingTopic5);
        this.componentesTrendingTopic.add(trendingTopic6);
        this.componentesTrendingTopic.add(trendingTopic7);
        this.componentesTrendingTopic.add(trendingTopic8);
        this.componentesTrendingTopic.add(trendingTopic9);
        this.componentesTrendingTopic.add(trendingTopic10);

        this.componentesTweet = new ArrayList<>();
        this.componentesTweet.add(tweet1);
        this.componentesTweet.add(tweet2);
        this.componentesTweet.add(tweet3);
        this.componentesTweet.add(tweet4);
        this.componentesTweet.add(tweet5);
        this.componentesTweet.add(tweet6);
        this.componentesTweet.add(tweet7);
        this.componentesTweet.add(tweet8);
        this.componentesTweet.add(tweet9);
        this.componentesTweet.add(tweet10);
    }

    private void inicializarTrendingTopics(String lugar) {
        HashMap<String, Integer> tt = BBDD.getWoeidTrendingTopic();
        int woeid = tt.get(lugar);

        this.jLabelLugarTrendingTopics.setText(lugar);
        Trend[] trendingTopics = gestionTwitter.getTrendingTopics(woeid);
        int i = 0;
        for (TrendingTopic componente : this.componentesTrendingTopic) {
            componente.inicializarComponente(trendingTopics[i]);
            i++;
        }
    }

    private void inicializarTweets() {
        List<Status> tweets = gestionTwitter.getUltimosTweetsUsuariosSeguidos();
        int i = 0;
        for (Tweet componente : componentesTweet) {
            componente.inicializarComponente(tweets.get(i));
            i++;
        }
    }

    private void aplicarListenerBotones() {
        final Color azulOscuro = new Color(29, 161, 242);
        final Color azulClaro = new Color(128, 216, 255);
        final Color rojo = new Color(255, 0, 0);

        listener.cambiarColorAlPasarPorEncima(jButtonAjustes, azulClaro, rojo);
        listener.cambiarColorAlPasarPorEncima(jButtonAjustes, azulClaro, azulOscuro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTrendingTopics = new javax.swing.JPanel();
        trendingTopic1 = new componentes.TrendingTopic();
        trendingTopic2 = new componentes.TrendingTopic();
        trendingTopic3 = new componentes.TrendingTopic();
        trendingTopic4 = new componentes.TrendingTopic();
        trendingTopic5 = new componentes.TrendingTopic();
        trendingTopic6 = new componentes.TrendingTopic();
        trendingTopic7 = new componentes.TrendingTopic();
        trendingTopic8 = new componentes.TrendingTopic();
        trendingTopic9 = new componentes.TrendingTopic();
        trendingTopic10 = new componentes.TrendingTopic();
        jLabelTituloTrendingTopics = new javax.swing.JLabel();
        jLabelLugarTrendingTopics = new javax.swing.JLabel();
        jButtonAjustes = new javax.swing.JButton();
        buscador = new componentes.Buscar();
        jScrollPaneTweets = new javax.swing.JScrollPane();
        jPanelTweets = new javax.swing.JPanel();
        tweet1 = new componentes.Tweet();
        tweet2 = new componentes.Tweet();
        tweet3 = new componentes.Tweet();
        tweet4 = new componentes.Tweet();
        tweet5 = new componentes.Tweet();
        tweet6 = new componentes.Tweet();
        tweet7 = new componentes.Tweet();
        tweet8 = new componentes.Tweet();
        tweet9 = new componentes.Tweet();
        tweet10 = new componentes.Tweet();
        nuevoTweet = new componentes.NuevoTweet();
        usuario = new componentes.Usuario();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jLabelTituloTrendingTopics.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelTituloTrendingTopics.setText("Trending Topics");

        jLabelLugarTrendingTopics.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanelTrendingTopicsLayout = new javax.swing.GroupLayout(jPanelTrendingTopics);
        jPanelTrendingTopics.setLayout(jPanelTrendingTopicsLayout);
        jPanelTrendingTopicsLayout.setHorizontalGroup(
            jPanelTrendingTopicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrendingTopicsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrendingTopicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trendingTopic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trendingTopic3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trendingTopic4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trendingTopic5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trendingTopic6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trendingTopic7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trendingTopic8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trendingTopic9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trendingTopic10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTrendingTopicsLayout.createSequentialGroup()
                        .addComponent(jLabelTituloTrendingTopics, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabelLugarTrendingTopics, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trendingTopic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTrendingTopicsLayout.setVerticalGroup(
            jPanelTrendingTopicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrendingTopicsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTrendingTopicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloTrendingTopics, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLugarTrendingTopics, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(trendingTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingTopic10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ajustes_blanco.png"))); // NOI18N
        jButtonAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjustesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTweetsLayout = new javax.swing.GroupLayout(jPanelTweets);
        jPanelTweets.setLayout(jPanelTweetsLayout);
        jPanelTweetsLayout.setHorizontalGroup(
            jPanelTweetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTweetsLayout.createSequentialGroup()
                .addGroup(jPanelTweetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tweet1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tweet2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(tweet3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(tweet4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(tweet5, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(tweet6, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(tweet7, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(tweet8, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(tweet9, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(tweet10, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTweetsLayout.setVerticalGroup(
            jPanelTweetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTweetsLayout.createSequentialGroup()
                .addComponent(tweet1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweet10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPaneTweets.setViewportView(jPanelTweets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTrendingTopics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAjustes))
                    .addComponent(nuevoTweet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneTweets))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTrendingTopics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(nuevoTweet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneTweets, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjustesActionPerformed
        PantallaAjustes ventana = new PantallaAjustes(padre, true);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_jButtonAjustesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.Buscar buscador;
    private javax.swing.JButton jButtonAjustes;
    private javax.swing.JLabel jLabelLugarTrendingTopics;
    private javax.swing.JLabel jLabelTituloTrendingTopics;
    private javax.swing.JPanel jPanelTrendingTopics;
    private javax.swing.JPanel jPanelTweets;
    private javax.swing.JScrollPane jScrollPaneTweets;
    private componentes.NuevoTweet nuevoTweet;
    private componentes.TrendingTopic trendingTopic1;
    private componentes.TrendingTopic trendingTopic10;
    private componentes.TrendingTopic trendingTopic2;
    private componentes.TrendingTopic trendingTopic3;
    private componentes.TrendingTopic trendingTopic4;
    private componentes.TrendingTopic trendingTopic5;
    private componentes.TrendingTopic trendingTopic6;
    private componentes.TrendingTopic trendingTopic7;
    private componentes.TrendingTopic trendingTopic8;
    private componentes.TrendingTopic trendingTopic9;
    private componentes.Tweet tweet1;
    private componentes.Tweet tweet10;
    private componentes.Tweet tweet2;
    private componentes.Tweet tweet3;
    private componentes.Tweet tweet4;
    private componentes.Tweet tweet5;
    private componentes.Tweet tweet6;
    private componentes.Tweet tweet7;
    private componentes.Tweet tweet8;
    private componentes.Tweet tweet9;
    private componentes.Usuario usuario;
    // End of variables declaration//GEN-END:variables
}
